### ISSUE TITLE
[M4] Configurar e implementar ADC y Systick para el sondeo de sensores.

### ISSUE THREAD

**Issue by franivan98** [ICOMP-UNC/Lenox-Legends#15]
vamos a usar dos canales para los dos sensores analogicos que tenemos:
* Sensor de Temperatura: Channel 0 del adc
* Pin para la medicion de bateria: Channel 1 del adc

en construccion...

**Comment by Lenox30** [comment]
No nos dimos cuenta de que el Systick es usado por RTOS, por lo que pasaremos todas las funciones de Systick a un Timer

**Comment by Mauricho** [comment]
Se ha logrado leer una señal analógica por el pin A0, y su valor pasarlo a la computadora mediante la comunicaión UART (para ello se utilizo el módulo FTDI). El valor leído define el duty cycle de la señal PWM, la cual se fue observando su comportamiento en un osciloscopio (para ver como cambiaba su ancho), y se conecto un led para hacer más visual el efecto (su brillo aumenta si aumenta el ancho de la seña, su brillo disminuye si el ancho disminuye).

**Comment by Lenox30** [comment]
Se completo la tarea con exito!
