### ISSUE TITLE
Configuracion y ejecucion de DMA con UART

### ISSUE THREAD

**Issue by franivan98** [ICOMP-UNC/Lenox-Legends#19]

**Comment by Lenox30** [comment]
Esta en funcionamiento el canal 1 del DMA para pasar datos del canal 1 del ADC a una variable global "adc_value" ubicada en la memoria, para verificar el correcto funcionamiento del DMA decidi usar el codigo de UART ya verificado por @Mauricho para mandar y ver por la compu los datos que estan en la variable "adc_value"
