### ISSUE TITLE
Configuracion del entorno de desarrollo.

### ISSUE THREAD

**Issue by franivan98** [ICOMP-UNC/Lenox-Legends#5]
Tenemos que configurar y preparar el Visual Studio Code para poder trabajar con la STM32 y con Free RTOS.

Lista de Actividades:

- [x] Instalar la extension "PlatformIO".
- [x] Descargar e incluir la libreria "rtos" en el dicrectorio del proyecto. (Lo pasaron por el grupo de Discord)
- [x] Compilar un codigo de prueba. 

Vamos a cerrar la Issue cuando los 3 tengamos configurado el entorno

**Comment by franivan98** [comment]
Terminado por mi parte

**Comment by Lenox30** [comment]
Se instalo PlatformIO, se descargo la librearia rtos, se compila bien el programa sin embargo no puedo ver las librerias de la STM32 creo que por algun problema de visual studios

**Comment by Mauricho** [comment]
Se ha logrado instalar Visual Studio Code junto con la extensión PlatformIO para hacer parpadear el led P13 del puerto C de la STM32.

**Comment by Lenox30** [comment]
Dado que mi Visual Studio de Windows se rompio totalmente, decidi pasar a linux para probar desde 0 y se ha logrado instalar, compilar y ver todas las librerias tanto de RTOS como de libopencm3

**Comment by franivan98** [comment]
Listo, lo damos por cerrado
