### ISSUE TITLE
Capacitacion en FreeRTOS

### ISSUE THREAD

**Issue by franivan98** [ICOMP-UNC/Lenox-Legends#6]
Vamos a tomar una breve capacitacion en FreeRTOS, aprendiendo los conocimientos basicos.
Vamos a estudiar los siguientes temas: 

- Tareas y Prioridades: 
- Colas y Semaforos
- Gestion de Tiempos y Retardos en FreeRTOS: vTaskDelay() y xTaskGetTickCount()

**Comment by franivan98** [comment]
Terminado por mi parte

**Comment by Mauricho** [comment]
Se han visto los vídeos de las clases por parte del profesor, y de la siguiente lista: https://www.youtube.com/playlist?list=PL-Hb9zZP9qC48GcXj_BsDipCPAzwcps6e&si=ogZHEduq_JDKci6Z.Creo haber entendido los conceptos y trataremos de implementarlo en el trabajo.
