### ISSUE TITLE
Diseño del Diagrama de Estados

### ISSUE THREAD

**Issue by franivan98** [ICOMP-UNC/Lenox-Legends#7]
Hacer el diagrama de estados que definan los modos de operacion del sistema.

**Comment by franivan98** [comment]
Primer Borrador
![3655071c-70b5-4d1c-bf73-d328dd54bf1e](https://github.com/user-attachments/assets/81b234c2-a69a-45aa-84cd-5fbf58284a3e)

**Comment by Lenox30** [comment]
Diagrama Secuencial de Dev, codigo con FreeRTOS

![TP-FInallll](https://github.com/user-attachments/assets/235a0da3-7adb-483a-9ac8-306206350cbe)
