### ISSUE TITLE
Diagrama Circuital

### ISSUE THREAD

**Issue by franivan98** [ICOMP-UNC/Lenox-Legends#8]
Definir las conexiones de la STM 32. 
Lista de componentes y pines a usar:

**Comment by Mauricho** [comment]
Versión 1 del esquemático.
![Esquematico](https://github.com/user-attachments/assets/5efbf9e6-824e-40b9-8ae8-b04cab684a3a)

**Comment by Mauricho** [comment]
Versión 2 del esquematico.
![Esquematico](https://github.com/user-attachments/assets/00d29a0d-71a4-4a34-b6a5-77ecd6afd218)

**Comment by Mauricho** [comment]
Se realizan modificaciones al diagrama circuital. Se actualiza según las últimas implentaciones.
![Esquematico](https://github.com/user-attachments/assets/6f78c757-54a4-461d-8e6b-e030b2ec1e0d)

**Comment by franivan98** [comment]
Agregar Pines para motores:
PA6: Motor 1
PA7: Motor 2

**Comment by Mauricho** [comment]
Se actualiza el esquematico y el diagrama circuital de acuerdo a los realizado.
![Esquematico](https://github.com/user-attachments/assets/c80fc5e3-1825-4a96-8f21-307932193607)
